version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: booksrus-db
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: booksrus
    ports: ["5432:5432"]
    volumes: [ "dbdata:/var/lib/postgresql/data" ]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d booksrus"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    container_name: booksrus-backend
    build:
      context: ./BooksRUs-Backend
      dockerfile: ./BooksRUs.Host/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:5050
      ConnectionStrings__Catalog: Host=db;Port=5432;Database=booksrus;Username=app;Password=app
      ConnectionStrings__ReadingList: Host=db;Port=5432;Database=booksrus;Username=app;Password=app
      ConnectionStrings__Default: Host=db;Port=5432;Database=booksrus;Username=app;Password=app
    ports: ["5050:5050"]
    depends_on:
      db:
        condition: service_healthy

  web:
    container_name: booksrus-web
    build:
      context: ./BooksRUs-WebApp
      dockerfile: ./Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:5050
        VITE_DEFAULT_USER_ID: u1-demo
    ports: ["5173:80"]
    depends_on:
      - backend

volumes:
  dbdata:
